import type { Metadata } from "next";
import { Heebo } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { AppShell } from "@/components/app-shell";
import { SwRegister } from "@/components/sw-register";
import "./globals.css";

const heebo = Heebo({
  variable: "--font-heebo",
  subsets: ["hebrew", "latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "shkedia",
  description: "ניהול סלונים ולקוחות",
  manifest: "/manifest.json",
  themeColor: "#ec4899",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "shkedia",
  },
  formatDetection: {
    telephone: false,
  },
  icons: {
    // Apple touch icon — PNG generated by: node scripts/generate-icons.mjs
    apple: "/icons/apple-icon.png",
    // SVG works immediately in all modern browsers without any build step
    icon:  "/icons/icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="he"
      dir="rtl"
      className={`${heebo.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col font-[family-name:var(--font-heebo)] bg-gray-50 dark:bg-indigo-950 transition-colors duration-300">
        <ThemeProvider>
          {/* SwRegister: silently registers /sw.js for PWA + future push support */}
          <SwRegister />
          {/* AppShell hides header/nav on /login, shows them everywhere else */}
          <AppShell>{children}</AppShell>
        </ThemeProvider>
      </body>
    </html>
  );
}
